[package]
name = "msp430-asm"
description = "Disassembler for msp430"
version = "0.1.0"
authors = ["jrozner"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
