[package]
name = "msp430-asm"
version = "0.1.0"
authors = ["jrozner"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
