use crate::emulate::*;
use crate::jxx::*;
use crate::single_operand::*;
use crate::two_operand::*;

use std::fmt;

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Instruction {
    // single operand instructions
    Rrc(Rrc),
    Swpb(Swpb),
    Rra(Rra),
    Sxt(Sxt),
    Push(Push),
    Call(Call),
    Reti(Reti),

    // Jxx instructions
    Jnz(Jnz),
    Jz(Jz),
    Jlo(Jlo),
    Jc(Jc),
    Jn(Jn),
    Jge(Jge),
    Jl(Jl),
    Jmp(Jmp),

    // two operand instructions
    Mov(Mov),
    Add(Add),
    Addc(Addc),
    Subc(Subc),
    Sub(Sub),
    Cmp(Cmp),
    Dadd(Dadd),
    Bit(Bit),
    Bic(Bic),
    Bis(Bis),
    Xor(Xor),
    And(And),

    // emulated
    Adc(Adc),
    Br(Br),
    Clr(Clr),
    Clrc(Clrc),
    Clrn(Clrn),
    Clrz(Clrz),
    Dadc(Dadc),
    Dec(Dec),
    Decd(Decd),
    Dint(Dint),
    Eint(Eint),
    Inc(Inc),
    Incd(Incd),
    Inv(Inv),
    Nop(Nop),
    Pop(Pop),
    Ret(Ret),
    Rla(Rla),
    Rlc(Rlc),
    Sbc(Sbc),
    Setc(Setc),
    Setn(Setn),
    Setz(Setz),
    Tst(Tst),
}

impl Instruction {
    pub fn len(&self) -> usize {
        match self {
            Self::Rrc(inst) => inst.len(),
            Self::Swpb(inst) => inst.len(),
            Self::Rra(inst) => inst.len(),
            Self::Sxt(inst) => inst.len(),
            Self::Push(inst) => inst.len(),
            Self::Call(inst) => inst.len(),
            Self::Reti(inst) => inst.len(),
            Self::Jnz(inst) => inst.len(),
            Self::Jz(inst) => inst.len(),
            Self::Jlo(inst) => inst.len(),
            Self::Jc(inst) => inst.len(),
            Self::Jn(inst) => inst.len(),
            Self::Jge(inst) => inst.len(),
            Self::Jl(inst) => inst.len(),
            Self::Jmp(inst) => inst.len(),
            Self::Mov(inst) => inst.len(),
            Self::Add(inst) => inst.len(),
            Self::Addc(inst) => inst.len(),
            Self::Subc(inst) => inst.len(),
            Self::Sub(inst) => inst.len(),
            Self::Cmp(inst) => inst.len(),
            Self::Dadd(inst) => inst.len(),
            Self::Bit(inst) => inst.len(),
            Self::Bic(inst) => inst.len(),
            Self::Bis(inst) => inst.len(),
            Self::Xor(inst) => inst.len(),
            Self::And(inst) => inst.len(),
            Self::Adc(inst) => inst.len(),
            Self::Br(inst) => inst.len(),
            Self::Clr(inst) => inst.len(),
            Self::Clrc(inst) => inst.len(),
            Self::Clrn(inst) => inst.len(),
            Self::Clrz(inst) => inst.len(),
            Self::Dadc(inst) => inst.len(),
            Self::Dec(inst) => inst.len(),
            Self::Decd(inst) => inst.len(),
            Self::Dint(inst) => inst.len(),
            Self::Eint(inst) => inst.len(),
            Self::Inc(inst) => inst.len(),
            Self::Incd(inst) => inst.len(),
            Self::Inv(inst) => inst.len(),
            Self::Nop(inst) => inst.len(),
            Self::Pop(inst) => inst.len(),
            Self::Ret(inst) => inst.len(),
            Self::Rla(inst) => inst.len(),
            Self::Rlc(inst) => inst.len(),
            Self::Sbc(inst) => inst.len(),
            Self::Setc(inst) => inst.len(),
            Self::Setn(inst) => inst.len(),
            Self::Setz(inst) => inst.len(),
            Self::Tst(inst) => inst.len(),
        }
    }
}

impl fmt::Display for Instruction {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Rrc(inst) => write!(f, "{}", inst),
            Self::Swpb(inst) => write!(f, "{}", inst),
            Self::Rra(inst) => write!(f, "{}", inst),
            Self::Sxt(inst) => write!(f, "{}", inst),
            Self::Push(inst) => write!(f, "{}", inst),
            Self::Call(inst) => write!(f, "{}", inst),
            Self::Reti(inst) => write!(f, "{}", inst),
            Self::Jnz(inst) => write!(f, "{}", inst),
            Self::Jz(inst) => write!(f, "{}", inst),
            Self::Jlo(inst) => write!(f, "{}", inst),
            Self::Jc(inst) => write!(f, "{}", inst),
            Self::Jn(inst) => write!(f, "{}", inst),
            Self::Jge(inst) => write!(f, "{}", inst),
            Self::Jl(inst) => write!(f, "{}", inst),
            Self::Jmp(inst) => write!(f, "{}", inst),
            Self::Mov(inst) => write!(f, "{}", inst),
            Self::Add(inst) => write!(f, "{}", inst),
            Self::Addc(inst) => write!(f, "{}", inst),
            Self::Subc(inst) => write!(f, "{}", inst),
            Self::Sub(inst) => write!(f, "{}", inst),
            Self::Cmp(inst) => write!(f, "{}", inst),
            Self::Dadd(inst) => write!(f, "{}", inst),
            Self::Bit(inst) => write!(f, "{}", inst),
            Self::Bic(inst) => write!(f, "{}", inst),
            Self::Bis(inst) => write!(f, "{}", inst),
            Self::Xor(inst) => write!(f, "{}", inst),
            Self::And(inst) => write!(f, "{}", inst),
            Self::Adc(inst) => write!(f, "{}", inst),
            Self::Br(inst) => write!(f, "{}", inst),
            Self::Clr(inst) => write!(f, "{}", inst),
            Self::Clrc(inst) => write!(f, "{}", inst),
            Self::Clrn(inst) => write!(f, "{}", inst),
            Self::Clrz(inst) => write!(f, "{}", inst),
            Self::Dadc(inst) => write!(f, "{}", inst),
            Self::Dec(inst) => write!(f, "{}", inst),
            Self::Decd(inst) => write!(f, "{}", inst),
            Self::Dint(inst) => write!(f, "{}", inst),
            Self::Eint(inst) => write!(f, "{}", inst),
            Self::Inc(inst) => write!(f, "{}", inst),
            Self::Incd(inst) => write!(f, "{}", inst),
            Self::Inv(inst) => write!(f, "{}", inst),
            Self::Nop(inst) => write!(f, "{}", inst),
            Self::Pop(inst) => write!(f, "{}", inst),
            Self::Ret(inst) => write!(f, "{}", inst),
            Self::Rla(inst) => write!(f, "{}", inst),
            Self::Rlc(inst) => write!(f, "{}", inst),
            Self::Sbc(inst) => write!(f, "{}", inst),
            Self::Setc(inst) => write!(f, "{}", inst),
            Self::Setn(inst) => write!(f, "{}", inst),
            Self::Setz(inst) => write!(f, "{}", inst),
            Self::Tst(inst) => write!(f, "{}", inst),
        }
    }
}
