use crate::emulate::*;
use crate::jxx::*;
use crate::single_operand::*;
use crate::two_operand::*;

use std::fmt;

#[derive(Debug, Clone, PartialEq)]
pub enum Instruction {
    // single operand instructions
    Rrc(Rrc),
    Swpb(Swpb),
    Rra(Rra),
    Sxt(Sxt),
    Push(Push),
    Call(Call),
    Reti(Reti),

    // Jxx instructions
    Jnz(Jnz),
    Jz(Jz),
    Jlo(Jlo),
    Jc(Jc),
    Jn(Jn),
    Jge(Jge),
    Jl(Jl),
    Jmp(Jmp),

    // two operand instructions
    Mov(Mov),
    Add(Add),
    Addc(Addc),
    Subc(Subc),
    Sub(Sub),
    Cmp(Cmp),
    Dadd(Dadd),
    Bit(Bit),
    Bic(Bic),
    Bis(Bis),
    Xor(Xor),
    And(And),

    // emulated
    Adc(Adc),
    Br(Br),
    Clr(Clr),
    Clrc(Clrc),
    Clrn(Clrn),
    Clrz(Clrz),
    Dadc(Dadc),
    Dec(Dec),
    Decd(Decd),
    Dint(Dint),
    Eint(Eint),
    Inc(Inc),
    Incd(Incd),
    Inv(Inv),
    Nop(Nop),
    Pop(Pop),
    Ret(Ret),
    Rla(Rla),
    Rlc(Rlc),
    Sbc(Sbc),
    Setc(Setc),
    Setn(Setn),
    Setz(Setz),
    Tst(Tst),
}

impl Instruction {
    pub fn len(&self) -> usize {
        match self {
            Instruction::Rrc(inst) => inst.len(),
            Instruction::Swpb(inst) => inst.len(),
            Instruction::Rra(inst) => inst.len(),
            Instruction::Sxt(inst) => inst.len(),
            Instruction::Push(inst) => inst.len(),
            Instruction::Call(inst) => inst.len(),
            Instruction::Reti(inst) => inst.len(),
            Instruction::Jnz(inst) => inst.len(),
            Instruction::Jz(inst) => inst.len(),
            Instruction::Jlo(inst) => inst.len(),
            Instruction::Jc(inst) => inst.len(),
            Instruction::Jn(inst) => inst.len(),
            Instruction::Jge(inst) => inst.len(),
            Instruction::Jl(inst) => inst.len(),
            Instruction::Jmp(inst) => inst.len(),
            Instruction::Mov(inst) => inst.len(),
            Instruction::Add(inst) => inst.len(),
            Instruction::Addc(inst) => inst.len(),
            Instruction::Subc(inst) => inst.len(),
            Instruction::Sub(inst) => inst.len(),
            Instruction::Cmp(inst) => inst.len(),
            Instruction::Dadd(inst) => inst.len(),
            Instruction::Bit(inst) => inst.len(),
            Instruction::Bic(inst) => inst.len(),
            Instruction::Bis(inst) => inst.len(),
            Instruction::Xor(inst) => inst.len(),
            Instruction::And(inst) => inst.len(),
            Instruction::Adc(inst) => inst.len(),
            Instruction::Br(inst) => inst.len(),
            Instruction::Clr(inst) => inst.len(),
            Instruction::Clrc(inst) => inst.len(),
            Instruction::Clrn(inst) => inst.len(),
            Instruction::Clrz(inst) => inst.len(),
            Instruction::Dadc(inst) => inst.len(),
            Instruction::Dec(inst) => inst.len(),
            Instruction::Decd(inst) => inst.len(),
            Instruction::Dint(inst) => inst.len(),
            Instruction::Eint(inst) => inst.len(),
            Instruction::Inc(inst) => inst.len(),
            Instruction::Incd(inst) => inst.len(),
            Instruction::Inv(inst) => inst.len(),
            Instruction::Nop(inst) => inst.len(),
            Instruction::Pop(inst) => inst.len(),
            Instruction::Ret(inst) => inst.len(),
            Instruction::Rla(inst) => inst.len(),
            Instruction::Rlc(inst) => inst.len(),
            Instruction::Sbc(inst) => inst.len(),
            Instruction::Setc(inst) => inst.len(),
            Instruction::Setn(inst) => inst.len(),
            Instruction::Setz(inst) => inst.len(),
            Instruction::Tst(inst) => inst.len(),
        }
    }
}

impl fmt::Display for Instruction {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Instruction::Rrc(inst) => write!(f, "{}", inst),
            Instruction::Swpb(inst) => write!(f, "{}", inst),
            Instruction::Rra(inst) => write!(f, "{}", inst),
            Instruction::Sxt(inst) => write!(f, "{}", inst),
            Instruction::Push(inst) => write!(f, "{}", inst),
            Instruction::Call(inst) => write!(f, "{}", inst),
            Instruction::Reti(inst) => write!(f, "{}", inst),
            Instruction::Jnz(inst) => write!(f, "{}", inst),
            Instruction::Jz(inst) => write!(f, "{}", inst),
            Instruction::Jlo(inst) => write!(f, "{}", inst),
            Instruction::Jc(inst) => write!(f, "{}", inst),
            Instruction::Jn(inst) => write!(f, "{}", inst),
            Instruction::Jge(inst) => write!(f, "{}", inst),
            Instruction::Jl(inst) => write!(f, "{}", inst),
            Instruction::Jmp(inst) => write!(f, "{}", inst),
            Instruction::Mov(inst) => write!(f, "{}", inst),
            Instruction::Add(inst) => write!(f, "{}", inst),
            Instruction::Addc(inst) => write!(f, "{}", inst),
            Instruction::Subc(inst) => write!(f, "{}", inst),
            Instruction::Sub(inst) => write!(f, "{}", inst),
            Instruction::Cmp(inst) => write!(f, "{}", inst),
            Instruction::Dadd(inst) => write!(f, "{}", inst),
            Instruction::Bit(inst) => write!(f, "{}", inst),
            Instruction::Bic(inst) => write!(f, "{}", inst),
            Instruction::Bis(inst) => write!(f, "{}", inst),
            Instruction::Xor(inst) => write!(f, "{}", inst),
            Instruction::And(inst) => write!(f, "{}", inst),
            Instruction::Adc(inst) => write!(f, "{}", inst),
            Instruction::Br(inst) => write!(f, "{}", inst),
            Instruction::Clr(inst) => write!(f, "{}", inst),
            Instruction::Clrc(inst) => write!(f, "{}", inst),
            Instruction::Clrn(inst) => write!(f, "{}", inst),
            Instruction::Clrz(inst) => write!(f, "{}", inst),
            Instruction::Dadc(inst) => write!(f, "{}", inst),
            Instruction::Dec(inst) => write!(f, "{}", inst),
            Instruction::Decd(inst) => write!(f, "{}", inst),
            Instruction::Dint(inst) => write!(f, "{}", inst),
            Instruction::Eint(inst) => write!(f, "{}", inst),
            Instruction::Inc(inst) => write!(f, "{}", inst),
            Instruction::Incd(inst) => write!(f, "{}", inst),
            Instruction::Inv(inst) => write!(f, "{}", inst),
            Instruction::Nop(inst) => write!(f, "{}", inst),
            Instruction::Pop(inst) => write!(f, "{}", inst),
            Instruction::Ret(inst) => write!(f, "{}", inst),
            Instruction::Rla(inst) => write!(f, "{}", inst),
            Instruction::Rlc(inst) => write!(f, "{}", inst),
            Instruction::Sbc(inst) => write!(f, "{}", inst),
            Instruction::Setc(inst) => write!(f, "{}", inst),
            Instruction::Setn(inst) => write!(f, "{}", inst),
            Instruction::Setz(inst) => write!(f, "{}", inst),
            Instruction::Tst(inst) => write!(f, "{}", inst),
        }
    }
}
